name: Build Book

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra

      - name: Build PDF
        run: make

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: book
          path: book.pdf
